// Static fallback country data
export interface StaticCountry {
  name: {
    common: string;
    official: string;
  };
  flags: {
    png: string;
    svg: string;
    emoji: string;
  };
  cca2: string;
}

export const FALLBACK_COUNTRIES: StaticCountry[] = [
  { name: { common: "Afghanistan", official: "Islamic Republic of Afghanistan" }, flags: { png: "", svg: "", emoji: "🇦🇫" }, cca2: "AF" },
  { name: { common: "Albania", official: "Republic of Albania" }, flags: { png: "", svg: "", emoji: "🇦🇱" }, cca2: "AL" },
  { name: { common: "Algeria", official: "People's Democratic Republic of Algeria" }, flags: { png: "", svg: "", emoji: "🇩🇿" }, cca2: "DZ" },
  { name: { common: "Argentina", official: "Argentine Republic" }, flags: { png: "", svg: "", emoji: "🇦🇷" }, cca2: "AR" },
  { name: { common: "Armenia", official: "Republic of Armenia" }, flags: { png: "", svg: "", emoji: "🇦🇲" }, cca2: "AM" },
  { name: { common: "Australia", official: "Commonwealth of Australia" }, flags: { png: "", svg: "", emoji: "🇦🇺" }, cca2: "AU" },
  { name: { common: "Austria", official: "Republic of Austria" }, flags: { png: "", svg: "", emoji: "🇦🇹" }, cca2: "AT" },
  { name: { common: "Azerbaijan", official: "Republic of Azerbaijan" }, flags: { png: "", svg: "", emoji: "🇦🇿" }, cca2: "AZ" },
  { name: { common: "Bahrain", official: "Kingdom of Bahrain" }, flags: { png: "", svg: "", emoji: "🇧🇭" }, cca2: "BH" },
  { name: { common: "Bangladesh", official: "People's Republic of Bangladesh" }, flags: { png: "", svg: "", emoji: "🇧🇩" }, cca2: "BD" },
  { name: { common: "Belarus", official: "Republic of Belarus" }, flags: { png: "", svg: "", emoji: "🇧🇾" }, cca2: "BY" },
  { name: { common: "Belgium", official: "Kingdom of Belgium" }, flags: { png: "", svg: "", emoji: "🇧🇪" }, cca2: "BE" },
  { name: { common: "Bolivia", official: "Plurinational State of Bolivia" }, flags: { png: "", svg: "", emoji: "🇧🇴" }, cca2: "BO" },
  { name: { common: "Bosnia and Herzegovina", official: "Bosnia and Herzegovina" }, flags: { png: "", svg: "", emoji: "🇧🇦" }, cca2: "BA" },
  { name: { common: "Brazil", official: "Federative Republic of Brazil" }, flags: { png: "", svg: "", emoji: "🇧🇷" }, cca2: "BR" },
  { name: { common: "Bulgaria", official: "Republic of Bulgaria" }, flags: { png: "", svg: "", emoji: "🇧🇬" }, cca2: "BG" },
  { name: { common: "Cambodia", official: "Kingdom of Cambodia" }, flags: { png: "", svg: "", emoji: "🇰🇭" }, cca2: "KH" },
  { name: { common: "Canada", official: "Canada" }, flags: { png: "", svg: "", emoji: "🇨🇦" }, cca2: "CA" },
  { name: { common: "Chile", official: "Republic of Chile" }, flags: { png: "", svg: "", emoji: "🇨🇱" }, cca2: "CL" },
  { name: { common: "China", official: "People's Republic of China" }, flags: { png: "", svg: "", emoji: "🇨🇳" }, cca2: "CN" },
  { name: { common: "Colombia", official: "Republic of Colombia" }, flags: { png: "", svg: "", emoji: "🇨🇴" }, cca2: "CO" },
  { name: { common: "Croatia", official: "Republic of Croatia" }, flags: { png: "", svg: "", emoji: "🇭🇷" }, cca2: "HR" },
  { name: { common: "Czech Republic", official: "Czech Republic" }, flags: { png: "", svg: "", emoji: "🇨🇿" }, cca2: "CZ" },
  { name: { common: "Denmark", official: "Kingdom of Denmark" }, flags: { png: "", svg: "", emoji: "🇩🇰" }, cca2: "DK" },
  { name: { common: "Ecuador", official: "Republic of Ecuador" }, flags: { png: "", svg: "", emoji: "🇪🇨" }, cca2: "EC" },
  { name: { common: "Egypt", official: "Arab Republic of Egypt" }, flags: { png: "", svg: "", emoji: "🇪🇬" }, cca2: "EG" },
  { name: { common: "Estonia", official: "Republic of Estonia" }, flags: { png: "", svg: "", emoji: "🇪🇪" }, cca2: "EE" },
  { name: { common: "Ethiopia", official: "Federal Democratic Republic of Ethiopia" }, flags: { png: "", svg: "", emoji: "🇪🇹" }, cca2: "ET" },
  { name: { common: "Finland", official: "Republic of Finland" }, flags: { png: "", svg: "", emoji: "🇫🇮" }, cca2: "FI" },
  { name: { common: "France", official: "French Republic" }, flags: { png: "", svg: "", emoji: "🇫🇷" }, cca2: "FR" },
  { name: { common: "Georgia", official: "Georgia" }, flags: { png: "", svg: "", emoji: "🇬🇪" }, cca2: "GE" },
  { name: { common: "Germany", official: "Federal Republic of Germany" }, flags: { png: "", svg: "", emoji: "🇩🇪" }, cca2: "DE" },
  { name: { common: "Ghana", official: "Republic of Ghana" }, flags: { png: "", svg: "", emoji: "🇬🇭" }, cca2: "GH" },
  { name: { common: "Greece", official: "Hellenic Republic" }, flags: { png: "", svg: "", emoji: "🇬🇷" }, cca2: "GR" },
  { name: { common: "Hungary", official: "Hungary" }, flags: { png: "", svg: "", emoji: "🇭🇺" }, cca2: "HU" },
  { name: { common: "Iceland", official: "Iceland" }, flags: { png: "", svg: "", emoji: "🇮🇸" }, cca2: "IS" },
  { name: { common: "India", official: "Republic of India" }, flags: { png: "", svg: "", emoji: "🇮🇳" }, cca2: "IN" },
  { name: { common: "Indonesia", official: "Republic of Indonesia" }, flags: { png: "", svg: "", emoji: "🇮🇩" }, cca2: "ID" },
  { name: { common: "Iran", official: "Islamic Republic of Iran" }, flags: { png: "", svg: "", emoji: "🇮🇷" }, cca2: "IR" },
  { name: { common: "Iraq", official: "Republic of Iraq" }, flags: { png: "", svg: "", emoji: "🇮🇶" }, cca2: "IQ" },
  { name: { common: "Ireland", official: "Republic of Ireland" }, flags: { png: "", svg: "", emoji: "🇮🇪" }, cca2: "IE" },
  { name: { common: "Israel", official: "State of Israel" }, flags: { png: "", svg: "", emoji: "🇮🇱" }, cca2: "IL" },
  { name: { common: "Italy", official: "Italian Republic" }, flags: { png: "", svg: "", emoji: "🇮🇹" }, cca2: "IT" },
  { name: { common: "Japan", official: "Japan" }, flags: { png: "", svg: "", emoji: "🇯🇵" }, cca2: "JP" },
  { name: { common: "Jordan", official: "Hashemite Kingdom of Jordan" }, flags: { png: "", svg: "", emoji: "🇯🇴" }, cca2: "JO" },
  { name: { common: "Kazakhstan", official: "Republic of Kazakhstan" }, flags: { png: "", svg: "", emoji: "🇰🇿" }, cca2: "KZ" },
  { name: { common: "Kenya", official: "Republic of Kenya" }, flags: { png: "", svg: "", emoji: "🇰🇪" }, cca2: "KE" },
  { name: { common: "Kuwait", official: "State of Kuwait" }, flags: { png: "", svg: "", emoji: "🇰🇼" }, cca2: "KW" },
  { name: { common: "Latvia", official: "Republic of Latvia" }, flags: { png: "", svg: "", emoji: "🇱🇻" }, cca2: "LV" },
  { name: { common: "Lebanon", official: "Lebanese Republic" }, flags: { png: "", svg: "", emoji: "🇱🇧" }, cca2: "LB" },
  { name: { common: "Lithuania", official: "Republic of Lithuania" }, flags: { png: "", svg: "", emoji: "🇱🇹" }, cca2: "LT" },
  { name: { common: "Luxembourg", official: "Grand Duchy of Luxembourg" }, flags: { png: "", svg: "", emoji: "🇱🇺" }, cca2: "LU" },
  { name: { common: "Malaysia", official: "Malaysia" }, flags: { png: "", svg: "", emoji: "🇲🇾" }, cca2: "MY" },
  { name: { common: "Mexico", official: "United Mexican States" }, flags: { png: "", svg: "", emoji: "🇲🇽" }, cca2: "MX" },
  { name: { common: "Morocco", official: "Kingdom of Morocco" }, flags: { png: "", svg: "", emoji: "🇲🇦" }, cca2: "MA" },
  { name: { common: "Netherlands", official: "Kingdom of the Netherlands" }, flags: { png: "", svg: "", emoji: "🇳🇱" }, cca2: "NL" },
  { name: { common: "New Zealand", official: "New Zealand" }, flags: { png: "", svg: "", emoji: "🇳🇿" }, cca2: "NZ" },
  { name: { common: "Nigeria", official: "Federal Republic of Nigeria" }, flags: { png: "", svg: "", emoji: "🇳🇬" }, cca2: "NG" },
  { name: { common: "North Korea", official: "Democratic People's Republic of Korea" }, flags: { png: "", svg: "", emoji: "🇰🇵" }, cca2: "KP" },
  { name: { common: "Norway", official: "Kingdom of Norway" }, flags: { png: "", svg: "", emoji: "🇳🇴" }, cca2: "NO" },
  { name: { common: "Oman", official: "Sultanate of Oman" }, flags: { png: "", svg: "", emoji: "🇴🇲" }, cca2: "OM" },
  { name: { common: "Pakistan", official: "Islamic Republic of Pakistan" }, flags: { png: "", svg: "", emoji: "🇵🇰" }, cca2: "PK" },
  { name: { common: "Peru", official: "Republic of Peru" }, flags: { png: "", svg: "", emoji: "🇵🇪" }, cca2: "PE" },
  { name: { common: "Philippines", official: "Republic of the Philippines" }, flags: { png: "", svg: "", emoji: "🇵🇭" }, cca2: "PH" },
  { name: { common: "Poland", official: "Republic of Poland" }, flags: { png: "", svg: "", emoji: "🇵🇱" }, cca2: "PL" },
  { name: { common: "Portugal", official: "Portuguese Republic" }, flags: { png: "", svg: "", emoji: "🇵🇹" }, cca2: "PT" },
  { name: { common: "Qatar", official: "State of Qatar" }, flags: { png: "", svg: "", emoji: "🇶🇦" }, cca2: "QA" },
  { name: { common: "Romania", official: "Romania" }, flags: { png: "", svg: "", emoji: "🇷🇴" }, cca2: "RO" },
  { name: { common: "Russia", official: "Russian Federation" }, flags: { png: "", svg: "", emoji: "🇷🇺" }, cca2: "RU" },
  { name: { common: "Saudi Arabia", official: "Kingdom of Saudi Arabia" }, flags: { png: "", svg: "", emoji: "🇸🇦" }, cca2: "SA" },
  { name: { common: "Serbia", official: "Republic of Serbia" }, flags: { png: "", svg: "", emoji: "🇷🇸" }, cca2: "RS" },
  { name: { common: "Singapore", official: "Republic of Singapore" }, flags: { png: "", svg: "", emoji: "🇸🇬" }, cca2: "SG" },
  { name: { common: "Slovakia", official: "Slovak Republic" }, flags: { png: "", svg: "", emoji: "🇸🇰" }, cca2: "SK" },
  { name: { common: "Slovenia", official: "Republic of Slovenia" }, flags: { png: "", svg: "", emoji: "🇸🇮" }, cca2: "SI" },
  { name: { common: "South Africa", official: "Republic of South Africa" }, flags: { png: "", svg: "", emoji: "🇿🇦" }, cca2: "ZA" },
  { name: { common: "South Korea", official: "Republic of Korea" }, flags: { png: "", svg: "", emoji: "🇰🇷" }, cca2: "KR" },
  { name: { common: "Spain", official: "Kingdom of Spain" }, flags: { png: "", svg: "", emoji: "🇪🇸" }, cca2: "ES" },
  { name: { common: "Sri Lanka", official: "Democratic Socialist Republic of Sri Lanka" }, flags: { png: "", svg: "", emoji: "🇱🇰" }, cca2: "LK" },
  { name: { common: "Sweden", official: "Kingdom of Sweden" }, flags: { png: "", svg: "", emoji: "🇸🇪" }, cca2: "SE" },
  { name: { common: "Switzerland", official: "Swiss Confederation" }, flags: { png: "", svg: "", emoji: "🇨🇭" }, cca2: "CH" },
  { name: { common: "Thailand", official: "Kingdom of Thailand" }, flags: { png: "", svg: "", emoji: "🇹🇭" }, cca2: "TH" },
  { name: { common: "Turkey", official: "Republic of Turkey" }, flags: { png: "", svg: "", emoji: "🇹🇷" }, cca2: "TR" },
  { name: { common: "Ukraine", official: "Ukraine" }, flags: { png: "", svg: "", emoji: "🇺🇦" }, cca2: "UA" },
  { name: { common: "United Arab Emirates", official: "United Arab Emirates" }, flags: { png: "", svg: "", emoji: "🇦🇪" }, cca2: "AE" },
  { name: { common: "United Kingdom", official: "United Kingdom of Great Britain and Northern Ireland" }, flags: { png: "", svg: "", emoji: "🇬🇧" }, cca2: "GB" },
  { name: { common: "United States", official: "United States of America" }, flags: { png: "", svg: "", emoji: "🇺🇸" }, cca2: "US" },
  { name: { common: "Uruguay", official: "Oriental Republic of Uruguay" }, flags: { png: "", svg: "", emoji: "🇺🇾" }, cca2: "UY" },
  { name: { common: "Venezuela", official: "Bolivarian Republic of Venezuela" }, flags: { png: "", svg: "", emoji: "🇻🇪" }, cca2: "VE" },
  { name: { common: "Vietnam", official: "Socialist Republic of Vietnam" }, flags: { png: "", svg: "", emoji: "🇻🇳" }, cca2: "VN" },
  { name: { common: "Yemen", official: "Republic of Yemen" }, flags: { png: "", svg: "", emoji: "🇾🇪" }, cca2: "YE" }
].sort((a, b) => a.name.common.localeCompare(b.name.common));